[package]
name = "kaspa-wallet"
description = "Kaspa wallet"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[features]
legacy-rpc = ["kaspa-cli/legacy-rpc"]
default = []

[dependencies]
kaspa-cli.workspace = true
tokio.workspace = true

[package.metadata.cargo-machete]
ignored = ["kaspa-cli"]
