[package]
name = "kaspa-testing-integration"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kaspa-alloc.workspace = true            # This changes the global allocator for all of the next dependencies so should be kept first
kaspa-addresses.workspace = true
kaspa-consensus-core.workspace = true
kaspa-consensus-notify.workspace = true
kaspa-consensus.workspace = true
kaspa-consensusmanager.workspace = true
kaspa-core.workspace = true
kaspa-grpc-client.workspace = true
kaspa-grpc-core.workspace = true
kaspa-hashes.workspace = true
kaspa-math.workspace = true
kaspa-notify.workspace = true
kaspa-rpc-core.workspace = true

async-channel.workspace = true
kaspad.workspace = true
faster-hex.workspace = true
flate2.workspace = true
futures-util.workspace = true
itertools.workspace = true
kaspa-database.workspace = true
kaspa-index-processor.workspace = true
kaspa-muhash.workspace = true
kaspa-txscript.workspace = true
kaspa-utils.workspace = true
kaspa-utxoindex.workspace = true
log.workspace = true
parking_lot.workspace = true
rand_distr.workspace = true
rand.workspace = true
rayon.workspace = true
secp256k1.workspace = true
serde_json.workspace = true
serde.workspace = true
tempfile.workspace = true
tokio.workspace = true

[dev-dependencies]
criterion.workspace = true
rand = { workspace = true, features = ["small_rng"] }
tokio = { workspace = true, features = ["rt", "macros"] }
kaspa-txscript-errors.workspace = true

[features]
html_reports = []
devnet-prealloc = ["kaspad/devnet-prealloc"]
