[package]
name = "kaspa-grpc-core"
description = "Kaspa gRPC core"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kaspa-consensus-core.workspace = true
kaspa-core.workspace = true
kaspa-notify.workspace = true
kaspa-rpc-core.workspace = true
kaspa-utils.workspace = true
faster-hex.workspace = true
paste.workspace = true
prost.workspace = true
tonic = { workspace = true, features = ["tls", "gzip"] }
workflow-core.workspace = true

[build-dependencies]
tonic-build = { workspace = true, features = ["prost"] }
