[package]
name = "kaspa-grpc-client"
description = "Kaspa gRPC client"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kaspa-core.workspace = true
kaspa-grpc-core.workspace = true
kaspa-notify.workspace = true
kaspa-rpc-core.workspace = true
kaspa-utils.workspace = true
kaspa-utils-tower.workspace = true

async-channel.workspace = true
async-stream.workspace = true
async-trait.workspace = true
futures.workspace = true
log.workspace = true
paste.workspace = true
rand.workspace = true
regex.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "time"] }
tonic = { workspace = true, features = ["gzip"] }

[package.metadata.cargo-machete]
ignored = ["log"]