[package]
name = "kaspa-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
async-channel.workspace = true
ahash = "0.8.3"
triggered = "0.1"
serde = "1.0.152"
