[package]
name = "utxoindex"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
hashes.workspace = true
thiserror.workspace = true
consensus-core.workspace = true
consensus.workspace = true
kaspa-core.workspace = true
kaspa-utils.workspace = true
log.workspace = true

futures = "0.3.25"
rocksdb = "0.19"
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
async-channel = { workspace = true}
tokio = { workspace = true}
rand = { workspace = true}

