[package]
name = "utxoindex"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
hashes.workspace = true
thiserror.workspace = true
rpc-core.workspace = true
kaspa-utils.workspace = true
kaspa-core.workspace = true
consensus-core.workspace = true
consensus.workspace = true
faster-hex.workspace = true
async-std.workspace = true
log.workspace = true
rand.workspace = true
indexmap.workspace = true
serde.workspace = true
bincode.workspace = true

rocksdb = "0.19"
async-trait = "0.1.57"
crossbeam = "0.8.2"
atomic_enum = "0.2.0"
futures = { version = "0.3" }
tonic = { version = "0.8", features = ["gzip"] }
prost = { version = "0.11" }
h2 = "0.3"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] } #94 "feature"] }
tokio-stream = "0.1"
triggered = "0.1"
rand_distr = "0.4"
serde_json = "1.0"
parking_lot = "0.12"

#[build-dependencies]
#tonic-build = { version = "0.8" }
