[package]
name = "utxoindex"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
hashes.workspace = true
thiserror.workspace = true
consensus-core.workspace = true
consensus.workspace = true
kaspa-core.workspace = true
log.workspace = true

rocksdb = "0.19"
triggered = "0.1"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
#[build-dependencies]
#tonic-build = { version = "0.8" }
