[package]
name = "utxoindex"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
hashes.workspace = true
thiserror.workspace = true
consensus-core.workspace = true
consensus.workspace = true
kaspa-core.workspace = true
kaspa-utils.workspace = true
addresses.workspace = true 
log.workspace = true

[dev-dependencies]
criterion.workspace = true
rand.workspace = true

#futures = "0.3.25"
tokio = { version = "1.24.2", features = ["time"] }
rocksdb = "0.19"
async-channel = "1.8.0"
triggered = "0.1"
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }